{"traceId":"d410e3ac7f304826e285f2775d987d3a","displayName":"GenerateMetadataOfPaperPdf","startTime":1751345530702,"endTime":1751345530704.8977,"spans":{"77e7253bf685e94d":{"spanId":"77e7253bf685e94d","traceId":"d410e3ac7f304826e285f2775d987d3a","startTime":1751345530702,"endTime":1751345530704.8977,"attributes":{"genkit:type":"action","genkit:metadata:subtype":"flow","genkit:name":"GenerateMetadataOfPaperPdf","genkit:isRoot":true,"genkit:path":"/{GenerateMetadataOfPaperPdf,t:flow}","genkit:metadata:context":"{}","genkit:input":"{\"doc_filepath\":\"./doc/https!arxiv.org!pdf!2505.17117.pdf\"}","genkit:state":"error","genkit:isFailureSource":true},"displayName":"GenerateMetadataOfPaperPdf","links":[],"instrumentationLibrary":{"name":"genkit-tracer","version":"v1"},"spanKind":"INTERNAL","sameProcessAsParentSpan":{"value":true},"status":{"code":2,"message":"INVALID_ARGUMENT: Must supply a `model` to `generate()` calls."},"timeEvents":{"timeEvent":[{"time":1751345530704.7842,"annotation":{"attributes":{"exception.type":"400","exception.message":"INVALID_ARGUMENT: Must supply a `model` to `generate()` calls.","exception.stacktrace":"GenkitError: INVALID_ARGUMENT: Must supply a `model` to `generate()` calls.\n    at new GenkitError (/Users/henryblanchette/Documents/doc-notes/node_modules/@genkit-ai/core/lib/error.js:46:5)\n    at resolveModel (/Users/henryblanchette/Documents/doc-notes/node_modules/@genkit-ai/ai/lib/model.js:218:27)\n    at processTicksAndRejections (native:7:39)"},"description":"exception"}}]}}}}